2024-11-15 00:06:50,060 - INFO - 开始克隆主仓库...
2024-11-15 00:06:50,061 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:06:50,062 - INFO - 任务失败，重试 1/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:06:55,063 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:06:55,063 - INFO - 任务失败，重试 2/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:06:55,064 - INFO - 执行任务失败后的恢复操作: GitCloneMain
2024-11-15 00:07:57,968 - INFO - 开始克隆主仓库...
2024-11-15 00:07:57,968 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:07:57,974 - INFO - 任务失败，重试 1/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:08:02,976 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:08:02,977 - INFO - 任务失败，重试 2/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:08:02,978 - INFO - 执行任务失败后的恢复操作: GitCloneMain
2024-11-15 00:08:48,501 - INFO - 开始克隆主仓库...
2024-11-15 00:08:48,501 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:08:48,501 - INFO - 任务失败，重试 1/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:08:53,502 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:08:53,502 - INFO - 任务失败，重试 2/2，错误: cannot access local variable 'env' where it is not associated with a value
2024-11-15 00:08:53,502 - INFO - 执行任务失败后的恢复操作: GitCloneMain
2024-11-15 00:10:22,420 - INFO - 开始克隆主仓库...
2024-11-15 00:10:22,421 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:10:28,435 - INFO - 仓库已经是最新的
2024-11-15 00:10:28,435 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:10:28,436 - INFO - 开始克隆 source 仓库...
2024-11-15 00:10:28,436 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:10:49,797 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:10:59,797 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:11:21,214 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:16:31,827 - INFO - 开始克隆主仓库...
2024-11-15 00:16:31,828 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:16:37,472 - INFO - 仓库已经是最新的
2024-11-15 00:16:37,473 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:16:37,473 - INFO - 开始克隆 source 仓库...
2024-11-15 00:16:37,474 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:16:42,055 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:16:52,056 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:16:54,271 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:20:03,804 - INFO - 开始执行任务: GitCloneMain
2024-11-15 00:20:03,805 - INFO - 开始克隆主仓库...
2024-11-15 00:20:03,805 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:20:09,497 - INFO - 仓库已经是最新的
2024-11-15 00:20:09,498 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:20:09,498 - INFO - 任务 GitCloneMain 执行成功
2024-11-15 00:20:09,498 - INFO - 开始执行任务: GitCloneSource
2024-11-15 00:20:09,498 - INFO - 开始克隆 source 仓库...
2024-11-15 00:20:09,499 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:20:11,641 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:20:21,641 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:20:23,835 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:20:23,836 - ERROR - 任务 GitCloneSource 执行失败: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:21:20,451 - INFO - 开始执行任务: GitCloneMain
2024-11-15 00:21:20,452 - INFO - 开始克隆主仓库...
2024-11-15 00:21:20,452 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:21:26,107 - INFO - 仓库已经是最新的
2024-11-15 00:21:26,107 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:21:26,108 - INFO - 任务 GitCloneMain 执行成功
2024-11-15 00:21:26,108 - INFO - 开始执行任务: ShellCommand
2024-11-15 00:21:26,108 - INFO - 开始执行 Shell 操作...
2024-11-15 00:21:26,108 - INFO - 正在执行命令: echo 'Hello, World!'
2024-11-15 00:21:26,144 - INFO - 命令执行成功: echo 'Hello, World!'
2024-11-15 00:21:26,144 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:21:26,177 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:26,177 - INFO - 任务失败，重试 1/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:31,178 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:21:31,207 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:31,208 - INFO - 任务失败，重试 2/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:36,209 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:21:36,238 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:36,238 - INFO - 任务失败，重试 3/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:36,238 - INFO - 执行任务失败后的恢复操作: ShellCommand
2024-11-15 00:21:36,239 - ERROR - 任务 ShellCommand 执行失败: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:21:36,239 - INFO - 开始执行任务: GitCloneSource
2024-11-15 00:21:36,240 - INFO - 开始克隆 source 仓库...
2024-11-15 00:21:36,240 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:21:38,491 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:21:48,493 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:21:50,714 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:21:50,714 - ERROR - 任务 GitCloneSource 执行失败: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:29:10,082 - INFO - 开始执行任务: GitCloneMain
2024-11-15 00:29:10,083 - INFO - 开始克隆主仓库...
2024-11-15 00:29:10,083 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:29:15,692 - INFO - 仓库已经是最新的
2024-11-15 00:29:15,693 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:29:15,693 - INFO - 任务 GitCloneMain 执行成功
2024-11-15 00:29:15,693 - INFO - 开始执行任务: ShellCommand
2024-11-15 00:29:15,694 - INFO - 开始执行 Shell 操作...
2024-11-15 00:29:15,694 - INFO - 正在执行命令: echo 'Hello, World!'
2024-11-15 00:29:15,729 - INFO - 命令执行成功: echo 'Hello, World!'
2024-11-15 00:29:15,729 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:29:15,763 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: None
2024-11-15 00:29:15,763 - INFO - 任务失败，重试 1/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:29:20,764 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:29:20,806 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: None
2024-11-15 00:29:20,806 - INFO - 任务失败，重试 2/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:29:25,807 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:29:25,843 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: None
2024-11-15 00:29:25,843 - INFO - 任务失败，重试 3/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:29:25,843 - INFO - 执行任务失败后的恢复操作: ShellCommand
2024-11-15 00:29:25,844 - ERROR - 任务 ShellCommand 执行失败: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:29:25,844 - INFO - 开始执行任务: GitCloneSource
2024-11-15 00:29:25,844 - INFO - 开始克隆 source 仓库...
2024-11-15 00:29:25,845 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:29:28,093 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:29:38,094 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:29:40,255 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:29:40,256 - ERROR - 任务 GitCloneSource 执行失败: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:37:11,191 - INFO - 开始执行任务: GitCloneMain
2024-11-15 00:37:11,191 - INFO - 开始克隆主仓库...
2024-11-15 00:37:11,192 - INFO - 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:37:16,915 - INFO - 仓库已经是最新的
2024-11-15 00:37:16,915 - INFO - Git pull 完成，仓库已更新
2024-11-15 00:37:16,916 - INFO - 任务 GitCloneMain 执行成功
2024-11-15 00:37:16,916 - INFO - 开始执行任务: ShellCommand
2024-11-15 00:37:16,916 - INFO - 开始执行 Shell 操作...
2024-11-15 00:37:16,916 - INFO - 正在执行命令: echo 'Hello, World!'
2024-11-15 00:37:16,951 - INFO - 命令执行成功: echo 'Hello, World!'
2024-11-15 00:37:16,951 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:37:16,983 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: 命令语法不正确。

2024-11-15 00:37:16,983 - INFO - 任务失败，重试 1/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:37:21,984 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:37:22,012 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: 命令语法不正确。

2024-11-15 00:37:22,013 - INFO - 任务失败，重试 2/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:37:27,013 - INFO - 正在执行命令: mkdir -p /path/to/dir
2024-11-15 00:37:27,053 - INFO - 命令执行失败: mkdir -p /path/to/dir, 错误: 命令语法不正确。

2024-11-15 00:37:27,053 - INFO - 任务失败，重试 3/3，错误: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:37:27,054 - INFO - 执行任务失败后的恢复操作: ShellCommand
2024-11-15 00:37:27,054 - ERROR - 任务 ShellCommand 执行失败: Command 'mkdir -p /path/to/dir' returned non-zero exit status 1.
2024-11-15 00:37:27,055 - INFO - 开始执行任务: GitCloneSource
2024-11-15 00:37:27,055 - INFO - 开始克隆 source 仓库...
2024-11-15 00:37:27,055 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:37:48,451 - INFO - 任务失败，重试 1/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:37:58,453 - INFO - source 仓库已存在，执行 git pull 更新仓库...
2024-11-15 00:38:42,772 - INFO - 任务失败，重试 2/2，错误: Command '['git', 'pull']' returned non-zero exit status 1.
2024-11-15 00:38:42,772 - ERROR - 任务 GitCloneSource 执行失败: Command '['git', 'pull']' returned non-zero exit status 1.
